import:
  - ~/.config/alacritty/themes/ayu_dark.yml

tabspaces: 2

env:
  TERM: alacritty

window:
  opacity: 0.90


scrolling:
  history: 1000

font:
  normal:
    family: sourcecodepro
    style: Regular

  bold:
    family: sourcecodepro
    style: Bold

  italic:
    family: sourcecodepro
    style: Italic

  bold_italic:
    family: sourcecodepro
    style: Bold Italic

  size: 8.5

cursor:
  unfocused_hollow: true

key_bindings:
  - {
    key: N, mods: Control|Shift, action: SpawnNewInstance
  }
