scrolling:
  history: 1000

tabspaces: 2

window:
  opacity: 0.95

font:
  normal:
    family: sourcecodepro
    style: Regular

  bold:
    family: sourcecodepro
    style: Bold

  italic:
    family: sourcecodepro
    style: Italic

  bold_italic:
    family: sourcecodepro
    style: Bold Italic

  size: 7.5

colors:
  # Default colors
  primary:
    background: '0x121212'
    foreground: '0xd0d0d0'

  # Normal colors
  normal:
    black:   '0x282828'
    red:     '0xd71a1a'
    green:   '0x57ba37'
    yellow:  '0xf0d50c'
    blue:    '0x91aadf'
    magenta: '0xcf73e6'
    cyan:    '0xb7cbf4'
    white:   '0xdedede'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xff0000'
    green:   '0xd8fa3b'
    yellow:  '0xe7c547'
    blue:    '0xb7cbf4'
    magenta: '0xb77ee0'
    cyan:    '0xa9c1de'
    white:   '0xeeeeee'

# Nord
#colors:
#  primary:
#    background: '#2E3440'
#    foreground: '#D8DEE9'
#
#  normal:
#    black: '#3B4252'
#    red: '#BF616A'
#    green: '#A3BE8C'
#    yellow: '#EBCB8B'
#    blue: '#81A1C1'
#    magenta: '#B48EAD'
#    cyan: '#88C0D0'
#    white: '#E5E9F0'
#
#  bright:
#    black: '#4C566A'
#    red: '#BF616A'
#    green: '#A3BE8C'
#    yellow: '#EBCB8B'
#    blue: '#81A1C1'
#    magenta: '#B48EAD'
#    cyan: '#8FBCBB'
#    white: '#ECEFF4'

cursor:
  unfocused_hollow: true

key_bindings:
  - {
    key: N, mods: Control|Shift, action: SpawnNewInstance
  }
