scrolling:
  history: 1000

font:
  normal:
    family: monospace
    style: Regular

  bold:
    family: monospace
    style: Bold

  italic:
    family: monospace
    style: Italic

  bold_italic:
    family: monospace
    style: Bold Italic

  size: 11

colors:
  primary:
    background: '#2E3440'
    foreground: '#D8DEE9'

  normal:
    black: '#3B4252'
    red: '#BF616A'
    green: '#A3BE8C'
    yellow: '#EBCB8B'
    blue: '#81A1C1'
    magenta: '#B48EAD'
    cyan: '#88C0D0'
    white: '#E5E9F0'

  bright:
    black: '#4C566A'
    red: '#BF616A'
    green: '#A3BE8C'
    yellow: '#EBCB8B'
    blue: '#81A1C1'
    magenta: '#B48EAD'
    cyan: '#8FBCBB'
    white: '#ECEFF4'

cursor:
  unfocused_hollow: true

key_bindings:
  - {
    key: N, mods: Control|Shift, action: SpawnNewInstance
  }
