icons_format = "{icon}"

[theme] 
name = "bad-wolf"

[icons]
name = "awesome"

[[block]]
block = "networkmanager"
interface_name_exclude = ['br\-[0-9a-f]{12}', 'docker\d+']
ap_format = "{ssid^16}   {strength:5}"
device_format = "{icon} {ap}"
primary_only = true

[[block]]
block = "sound"
driver = "pulseaudio"
format = "{output_description} {volume:5}"
step_width = 3
max_vol = 100

[[block]]
block = "battery"
interval = 10
format = "{percentage:4}   {time:5}"

[[block]]
block = "memory"
format_mem = " {mem_used}/{mem_total}  ({mem_used_percents})"
display_type = "memory"
interval = 5
warning_mem = 85
critical_mem = 95

[[block]]
block = "time"
interval = 5
format = "%F    %T"
